[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "AI for Motivation and Inspiration: Techniques and Strategies to Stay Motivated and Inspired with Artificial Intelligence"
